### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by g-braeunlich** [kivy-garden/matplotlib#2]
To include this flower as a dependency of a python package which itself is published on pypi, a requirement is that this flower is available on pypi. Otherwise an end user will have to manually install this flower.

Could we have a pypi release?

**Comment by misl6** [comment]
Hi @g-braeunlich !

Did you already had the chance to test `matplotlib` flower after has been moved to this new home?  (I did not, yet ...)
If yes, everything looks fine?

**Comment by tcaduser** [comment]
Please see Issue #1, as it won't work with matplotlib 3.8.0 without fixing.  If it is fixed, this would require updating the recipes for both Android and iOS, or making it backward compatible.

**Comment by patalex74** [comment]
Any news on how to solve this pb : "'FigureCanvasKivyAgg' object has no attribute 'resize_event'" with matplotlib 3.8.2 and Kivy-garden 0.1.5 on macOS ? without downgrading to matplotlib 3.7.2. ?
Thanks

**Comment by tcaduser** [comment]
Someone would have to modify the code, as was done for this other matplotlib widget
https://github.com/kivy-garden/garden.matplotlib/issues/84#issuecomment-1817507344

Perhaps @mp-007 has some guidance on how to fix the code.

**Comment by DocGarbanzo** [comment]
Hi all, it seems the matplotlib upgrade issue has been fixed. Would it be possible to push the package to pypi please? Newer version of setuptools require dependencies to be on pypi. And your package is really cool!

**Comment by g-braeunlich** [comment]
> Hi @g-braeunlich !
> 
> Did you already had the chance to test `matplotlib` flower after has been moved to this new home? (I did not, yet ...) If yes, everything looks fine?

Hi @misl6 Sorry for the very late reply (I somehow forgot to reply).
But answer yes: I tested it (at least our usecase) and did it again today.
Everything fine so far.

**Comment by DocGarbanzo** [comment]
All,

I have pushed the current version to pypi: https://pypi.org/project/kivy-garden.matplotlib/.

**Comment by misl6** [comment]
Hi @DocGarbanzo !

Good that someone is taking care about it, regarding this topic, can you please contact me back via e-mail or on Discord?
(You can find my contact details on my GitHub profile)

**Comment by DocGarbanzo** [comment]
> Hi @DocGarbanzo !
> 
> Good that someone is taking care about it, regarding this topic, can you please contact me back via e-mail or on Discord? (You can find my contact details on my GitHub profile)

Sorry for the radio silence, I had missed that message. I've contacted you via email.
